version: '3'
services:
  postgres:
    image: "postgres:13.2"
    environment:
      POSTGRES_DB: topical
      POSTGRES_USER: topical
      POSTGRES_PASSWORD: examplepassword
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data